//
//  OnBoardingPresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingPresentationLogic
{
    func presentBanners(response: OnBoarding.GetOnBoardingData.Response)
    func presentLogInScene(response: OnBoarding.GoToLogInSccen.Response)
}

class OnBoardingPresenter: OnBoardingPresentationLogic
{
   
    
  weak var viewController: OnBoardingDisplayLogic?
  
  // MARK: Privare Methods
    
    private func configureTableModel(from data: [OnBoardingModel]) -> [OnBoardingModel] {
        var tableModel = [OnBoardingModel]()
        tableModel.append(contentsOf: data.map{
            OnBoardingModel(image: $0.image, title: $0.title)
        })
        return tableModel
    }
    
    //MARK: PresentationLogic Methods

    func presentBanners(response: OnBoarding.GetOnBoardingData.Response) {
        let viewModel =  configureTableModel(from: response.data)
        viewController?.displayBanners(viewModel: OnBoarding.GetOnBoardingData.ViewModel(tableData: viewModel))
    }
    func presentLogInScene(response: OnBoarding.GoToLogInSccen.Response) {
        viewController?.displayLogInScene(viewModel: OnBoarding.GoToLogInSccen.ViewModel())
    }
}

