//
//  OnBoardingWorker.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnboardingWorkerLogic {
    
    func getModelArray() -> [OnBoardingModel]
}

final class OnBoardingWorker: OnboardingWorkerLogic {
    
    private let onBoardingTitles = onBanner.jobBanners
    
    func getModelArray() -> [OnBoardingModel] {
        
        var conteiner = [OnBoardingModel]()
        for (key, value) in onBoardingTitles {
            conteiner.append( OnBoardingModel(image: UIImage(named: key), title: value))
        }
        return conteiner
    }
}
