//
//  OnBoardingWorker.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol OnboardingWorkerLogic {
    func getModelArray() -> [OnBoardingModel]
}
class OnBoardingWorker: OnboardingWorkerLogic
{
    func getModelArray() -> [OnBoardingModel] {
        
        return [OnBoardingModel(image: UIImage(named: "job1"), title: "Find job offers from the most popular job listing sites"),
        OnBoardingModel(image: UIImage(named: "job2"), title: "Track all your job applicatons and don’t get lost in the process"),
        OnBoardingModel(image: UIImage(named: "job3"), title: "Start appliying and get a Job Now!")]
        
    }
}
