//
//  OnBoardingInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingBusinessLogic
{
    func getBanners(request: OnBoarding.GetOnBoardingData.Request)
}

protocol OnBoardingDataStore
{
    var bannersDataStore: OnBoardingModel? { get }
}

class OnBoardingInteractor: OnBoardingBusinessLogic, OnBoardingDataStore
{
 private var presenter: OnBoardingPresentationLogic?
 private var worker: OnBoardingWorker?
    
    var bannersDataStore: OnBoardingModel?
    var banners = [OnBoardingModel]()
  
    init(presenter: OnBoardingPresentationLogic, worker: OnBoardingWorker ) {
        self.presenter = presenter
        self.worker = worker
        
    }
  // MARK: Do something
  
  func getBanners(request: OnBoarding.GetOnBoardingData.Request)
  {
      guard let banners = worker?.getModelArray() else { return}
      self.banners = banners
      self.presenter?.presentBanners(response: OnBoarding.GetOnBoardingData.Response(data: self.banners))
  }
}
