//
//  OnBoardingRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OnBoardingRoutingLogic
{
  func navigateToAuthentication()
}

protocol OnBoardingDataPassing
{
  var dataStore: OnBoardingDataStore? { get }
}

class OnBoardingRouter: NSObject, OnBoardingRoutingLogic, OnBoardingDataPassing
{
    //MARK: Clean components
    
  weak var viewController: OnBoardingViewController?
  private(set) var dataStore: OnBoardingDataStore?
  
    //MARK: Object LifeCycle
    
    init(dataStore: OnBoardingDataStore ) {
        self.dataStore = dataStore
    }
    
  // MARK: Routing
    func navigateToAuthentication() {
        let destVc = AuthenticationConfiguration.configure()
        viewController?.navigationController?.pushViewController(destVc, animated: true)
    }
}
