//
//  EditProfileViewController.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileDisplayLogic: AnyObject
{
  func displaySomething(viewModel: EditProfile.Something.ViewModel)
}

class EditProfileViewController: UIViewController, EditProfileDisplayLogic
{
  var interactor: EditProfileBusinessLogic?
  var router: (NSObjectProtocol & EditProfileRoutingLogic & EditProfileDataPassing)?
    
    //MARK: UI Elements
    let searchButton: UIButton = {
        let btn = UIButton()
        btn.setImage(UIImage(systemName: "person.crop.square.fill"), for: .normal)
        btn.tintColor = hexStringToUIColor(hex: "#5583F7")
        return btn
    }()
    
    let headLineLB: UILabel = {
        let lb = UILabel()
        lb.text = "Profile"
        
        return lb
    }()
    

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = EditProfileInteractor()
    let presenter = EditProfilePresenter()
    let router = EditProfileRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = EditProfile.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: EditProfile.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
