//
//  EditProfilePresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfilePresentationLogic
{
  func presentSomething(response: EditProfile.Something.Response)
    func presentHomeScene()
}

class EditProfilePresenter: EditProfilePresentationLogic
{
   
    
  weak var viewController: EditProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EditProfile.Something.Response)
  {
    let viewModel = EditProfile.Something.ViewModel()
    viewController?.displayHomeScreen(viewModel: viewModel)
  }
    func presentHomeScene() {
        viewController?.displayHomeScreen(viewModel: EditProfile.Something.ViewModel())
    }
}
