//
//  TipsDetailsScenePresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 11.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TipsDetailsScenePresentationLogic
{
  func presentSomething(response: TipsDetailsScene.Something.Response)
}

class TipsDetailsScenePresenter: TipsDetailsScenePresentationLogic
{
  weak var viewController: TipsDetailsSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TipsDetailsScene.Something.Response)
  {
    let viewModel = TipsDetailsScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
