//
//  TipsDetailsSceneInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 11.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TipsDetailsSceneBusinessLogic
{
  func doSomething(request: TipsDetailsScene.Something.Request)
}

protocol TipsDetailsSceneDataStore
{
  //var name: String { get set }
}

class TipsDetailsSceneInteractor: TipsDetailsSceneBusinessLogic, TipsDetailsSceneDataStore
{
  var presenter: TipsDetailsScenePresentationLogic?
  var worker: TipsDetailsSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TipsDetailsScene.Something.Request)
  {
    worker = TipsDetailsSceneWorker()
    worker?.doSomeWork()
    
    let response = TipsDetailsScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
