//
//  TipsDetailsSceneViewController.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 11.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TipsDetailsSceneDisplayLogic: class
{
  func displaySomething(viewModel: TipsDetailsScene.Something.ViewModel)
}

class TipsDetailsSceneViewController: UIViewController, TipsDetailsSceneDisplayLogic
{
  var interactor: TipsDetailsSceneBusinessLogic?
  var router: (NSObjectProtocol & TipsDetailsSceneRoutingLogic & TipsDetailsSceneDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = TipsDetailsSceneInteractor()
    let presenter = TipsDetailsScenePresenter()
    let router = TipsDetailsSceneRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = TipsDetailsScene.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: TipsDetailsScene.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
