//
//  AuthenticationWorker.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseAuth
enum AuthError: Error {
    case badEmailFormat
    case badPassword
}
protocol AuthenticationWorkerLogic {
    func tryLogIn(email: String, pass: String, completion: @escaping (Result<Bool, Error>) -> Void)
}

final class AuthenticationWorker: AuthenticationWorkerLogic {
    func tryLogIn(email: String, pass: String, completion: @escaping (Result<(Bool), Error>) -> Void) {
        Auth.auth().signIn(withEmail: email, password: pass) { (user, error) in
            if let error = error {
                completion(.failure(error))
            } else {
                completion(.success(true))
            }
        }
    }
}
