//
//  AuthenticationPresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthenticationPresentationLogic
{
    func presentSomething(response: Authentication.LoginAction.Response)
}

class AuthenticationPresenter: AuthenticationPresentationLogic
{
  weak var viewController: AuthenticationDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: Authentication.LoginAction.Response)
  {
//    let viewModel = Authentication.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
