//
//  AuthenticationRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AuthenticationRoutingLogic
{
    func navigationToRegistration()
    func navigateToSomewhere(destination: UIViewController)
}

protocol AuthenticationDataPassing
{
  var dataStore: AuthenticationDataStore? { get }
}

class AuthenticationRouter: NSObject, AuthenticationRoutingLogic, AuthenticationDataPassing
{
    func navigationToRegistration() {
        let vc = RegistrationConfiguration.configure()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
  weak var viewController: AuthenticationViewController?
  var dataStore: AuthenticationDataStore?
    init(dataStore: AuthenticationDataStore ) {
   
        self.dataStore = dataStore
    }
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  func navigateToSomewhere( destination: UIViewController)
  {
//    source.show(destination, sender: nil)
      self.viewController?.present(destination, animated: true)
      
  }
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AuthenticationDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
