//
//  AuthenticationInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthenticationBusinessLogic
{
    func doSomething(request: Authentication.LoginAction.Request)
}

protocol AuthenticationDataStore
{
  //var name: String { get set }
}

class AuthenticationInteractor: AuthenticationBusinessLogic, AuthenticationDataStore
{
  var presenter: AuthenticationPresentationLogic?
  var worker: AuthenticationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func doSomething(request: Authentication.LoginAction.Request)
  {
    worker = AuthenticationWorker()
    worker?.doSomeWork()
    
      //let response = Authentication.LoginAction.Response(user: <#T##User#>)
    //presenter?.presentSomething(response: response)
  }
    
    private func checkEmail(from mail: String) -> Bool {
      mail.contains( "@" )
    }
}
