//
//  HomeScenePresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 07.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScenePresentationLogic
{
  func presentTipsData(response: HomeScene.GetTips.Response)
  func presentAllTips(response: HomeScene.ShowAllTips.Response)
}

class HomeScenePresenter
{
  weak var viewController: HomeSceneDisplayLogic?
  
  // MARK: Private Methods
    
    private func configureTableModel(from data: [TipsModel]) -> [TipsModel] {
        
       return data
    }
  
 
}

extension HomeScenePresenter: HomeScenePresentationLogic {
    func presentAllTips(response: HomeScene.ShowAllTips.Response) {
        viewController?.displayAllTipsScene(viewModel: HomeScene.ShowAllTips.ViewModel())
    }
    
    func presentTipsData(response: HomeScene.GetTips.Response)
    {
        let viewModel = configureTableModel(from: response.data)
        viewController?.displayTips(viewModel: HomeScene.GetTips.ViewModel(data: viewModel))
    }
}
