//
//  HomeSceneWorker.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 07.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol HomeSceneWorkerLogic {
    func fetchTips() async throws -> [TipsModel]
}
class HomeSceneWorker
{
    private var api: APIManager
    private let tipsUrl = ApiUrls.tips.rawValue
    
    init(api: APIManager) {
        self.api = api
    }
}
extension HomeSceneWorker: HomeSceneWorkerLogic {
    
    func fetchTips() async throws -> [TipsModel] {
        try await api.fetchData(urlString: tipsUrl, decodingType: [TipsModel].self)
        
    }
}
