//
//  HomeSceneRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 07.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeSceneRoutingLogic
{
    func navigateToAllTipsListScene()
    func navigateToDetailsScene()
    func navigateToAllJobsScene()
}

protocol HomeSceneDataPassing
{
    var dataStore: HomeSceneDataStore { get }
}

class HomeSceneRouter:  HomeSceneDataPassing
{
  
    
    
    weak var viewController: HomeSceneViewController?
    private(set) var dataStore: HomeSceneDataStore
    
    // MARK: Object Lifecycle
    
    init(dataStore: HomeSceneDataStore) {
        self.dataStore = dataStore
    }
}

extension HomeSceneRouter : HomeSceneRoutingLogic {
    // MARK: Navigation
    func navigateToDetailsScene() {
        print("router")
        guard let selectedTip = dataStore.selectedTip else { return }
        let destVc = TipsDetailsSceneConfiguration.configure(with: selectedTip)
        print("esaa",selectedTip)
        viewController?.navigationController?.pushViewController(destVc, animated: true)
        
    }
    
    func navigateToAllTipsListScene() {
        
        let passingData = dataStore.passingData
        let destVc = AllTipsListSceneConfiguration.configure(with: passingData)
        viewController?.navigationController?.pushViewController(destVc, animated: true)
    }
    func navigateToAllJobsScene() {
        let destVc = AlljobsListControllerConfiguration.configure(with: dataStore.passingJob)
        viewController?.navigationController?.pushViewController(destVc, animated: true)
    }
    
}
