//
//  HomeScenePresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 07.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScenePresentationLogic {
    
  func presentAllTips(response: HomeScene.ShowAllTips.Response)
  func presnetTipsDetails(response: HomeScene.SeeDetails.Response)
  func presentSelectedJobDetails(response: HomeScene.SeeJobDetails.Response)
  func presentAllJobs(response: HomeScene.ShowAllJobs.Response)
  func presentFilteredJobs(response: HomeScene.FilterJobs.Response)
  func presentjobsByCategory(response: HomeScene.FilterJobs.Response)
  func logOutScene(response: HomeScene.LogOut.Response)
  func presentCommomModel(response: HomeScene.GetCommonModel.Response)
}

final class HomeScenePresenter {
  weak var viewController: HomeSceneDisplayLogic?
}

extension HomeScenePresenter: HomeScenePresentationLogic {
    func presentCommomModel(response: HomeScene.GetCommonModel.Response) {
        let viewModel = response.data
        viewController?.displayCommonModel(viewModel: HomeScene.GetCommonModel.ViewModel(data: viewModel))
    }
    
    func logOutScene(response: HomeScene.LogOut.Response) {
        viewController?.logOut(viewModel: HomeScene.LogOut.ViewModel())
    }
    
    func presentjobsByCategory(response: HomeScene.FilterJobs.Response) {
        let viewModel  = response.data
        viewController?.displayJobsBycategory(viewModel: HomeScene.FilterJobs.ViewModel(data: viewModel))
    }
    
    func presentSelectedJobDetails(response: HomeScene.SeeJobDetails.Response) {
        viewController?.displaySelectedJobDetails(viewModel: HomeScene.SeeJobDetails.ViewModel())
    }
    
    func presentFilteredJobs(response: HomeScene.FilterJobs.Response) {
        let viewModel =  response.data
        viewController?.displayFilteredJobs(viewModel: HomeScene.FilterJobs.ViewModel(data: viewModel))
    }

    func presentAllJobs(response: HomeScene.ShowAllJobs.Response) {
        viewController?.displayAllJobsScene(viewModel: HomeScene.ShowAllJobs.ViewModel())
    }
    
    func presnetTipsDetails(response: HomeScene.SeeDetails.Response) {
        viewController?.displayTipDetails(viewModel: HomeScene.SeeDetails.ViewModel())
    }
    
    func presentAllTips(response: HomeScene.ShowAllTips.Response) {
        viewController?.displayAllTipsScene(viewModel: HomeScene.ShowAllTips.ViewModel())
    }
}
