//
//  RegistrationPresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationPresentationLogic {
    func presentSuccess(with message: String)
    func presentFailure(with message: String)
    func goToLogIngPage(response: Registration.GoToLogIn.Response)
}

final class RegistrationPresenter: RegistrationPresentationLogic {
  
    
    
  weak var viewController: RegistrationDisplayLogic?
  
  // MARK: PresentationLogic Methods
    
    func presentSuccess(with message: String) {
        self.viewController?.displayCreatingSuccess(message: message)
    }
    
    func presentFailure(with message: String) {
        self.viewController?.displayCreatingFailure(message: message)
    }
    
    func goToLogIngPage(response: Registration.GoToLogIn.Response) {
        viewController?.goToLogInPage(vieModel: Registration.GoToLogIn.ViewModel())
    }
}

