//
//  RegistrationWorker.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseAuth

protocol RegistrationWorkerLogic {
    func createUser(email: String, password: String, completionBlock: @escaping (_ success: Bool) -> Void)
    func checkValidity(email: UITextField, password: UITextField, rePassword: UITextField) -> String?
}

final class RegistrationWorker: RegistrationWorkerLogic {
    
    //MARK: RegistrationWorkerLogic Methods
    
    func checkValidity(email: UITextField, password: UITextField, rePassword: UITextField) -> String? {
        FieldsValidation.shared.validateFields(from: [email, password, rePassword], password: password, rePassword: rePassword)
    }

    func createUser(email: String, password: String, completionBlock: @escaping (_ success: Bool) -> Void) {
        Auth.auth().createUser(withEmail: email, password: password) {(result, error) in
            if error != nil {
                completionBlock(false)
            }  else {
                let db = Firestore.firestore()
                db.collection("users").addDocument(data: ["mail" : email,
                                                          "password": password]) { error in
                    if error != nil {
                        completionBlock(false)
                    }
                }
                completionBlock(true)
            }
        }
    }
}






