//
//  AllJobsListSceneRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 12.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AllJobsListSceneRoutingLogic {
  func navigateTpJobDetailsScene()
}

protocol AllJobsListSceneDataPassing {
  var dataStore: AllJobsListSceneDataStore? { get }
}

final class AllJobsListSceneRouter: AllJobsListSceneRoutingLogic, AllJobsListSceneDataPassing {

  weak var viewController: AllJobsListSceneViewController?
  var dataStore: AllJobsListSceneDataStore?

    // MARK: object LifeCycle
    init(dataStore: AllJobsListSceneDataStore) {
        self.dataStore = dataStore
    }
  // MARK: Routing
    func navigateTpJobDetailsScene() {

        guard let selectedJob = dataStore?.selectedJob else { return }

        let destVc = JobDetailsViewControllerConfiguration.configure(with: selectedJob)
        viewController?.navigationController?.pushViewController(destVc, animated: true )

    }
}
