//
//  AllJobsListSceneModels.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 12.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AllJobsListScene {
  // MARK: Use cases

  enum GetAllJobs {
    struct Request {
    }
    struct Response {
        var data: [JobModel]
    }
    struct ViewModel {
        var data: [JobModel]
    }
  }
    enum FilterJobs {
        struct Request {
            var keyword: String?
            var category: String?
        }
        struct Response {
            var data: [JobModel]
        }
        struct ViewModel {
            var data: [JobModel]
        }
    }
    enum SeeJobDetails {
        struct Request {
            var data: JobModel
        }
        struct Response {
        }
        struct ViewModel {
        }
    }

}
