//
//  AllJobsListSceneInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 12.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllJobsListSceneBusinessLogic
{
    func getAllJobs(request: AllJobsListScene.GetAllJobs.Request)
}

protocol AllJobsListSceneDataStore
{
  var myJobModel: [JobModel] { get }
}

class AllJobsListSceneInteractor:  AllJobsListSceneDataStore
{
    //MARK: Clean components
    
  var presenter: AllJobsListScenePresentationLogic?

    var myJobModel:  [JobModel]
    
  // MARK: Object LifeCycle
    
    init(presenter: AllJobsListScenePresentationLogic, myJobModel:  [JobModel]) {
        self.presenter = presenter
        self.myJobModel = myJobModel
    }
  

}

extension AllJobsListSceneInteractor: AllJobsListSceneBusinessLogic {
    func getAllJobs(request: AllJobsListScene.GetAllJobs.Request) {
   
        let response = AllJobsListScene.GetAllJobs.Response(data: self.myJobModel)
         presenter?.presentAllJobs(response: response)
    }
    
    
}
