//
//  AllTipsListSceneRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 11.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AllTipsListSceneRoutingLogic
{
  func navigateToTipsDetails()
}

protocol AllTipsListSceneDataPassing
{
  var dataStore: AllTipsListSceneDataStore? { get }
}

class AllTipsListSceneRouter: NSObject, AllTipsListSceneRoutingLogic, AllTipsListSceneDataPassing
{
  weak var viewController: AllTipsListSceneViewController?
 private(set) var dataStore: AllTipsListSceneDataStore?
  
    //MARK: Object LifeCycle
    
    init(dataStore: AllTipsListSceneDataStore) {
        self.dataStore = dataStore
    }

  // MARK: Navigation
  
    func navigateToTipsDetails() {
        guard let selectedTip = dataStore?.selectedTip else { return }
        let destVc = TipsDetailsSceneConfiguration.configure(with: selectedTip)
        viewController?.navigationController?.pushViewController(destVc, animated: true)
    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AllTipsListSceneDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
