//
//  JobDetailsSceneInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 15.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol JobDetailsSceneBusinessLogic
{
    func getDetails(request: JobDetailsScene.ShowDetails.Request)
}

protocol JobDetailsSceneDataStore
{
  var selectedJob: JobModel { get }
}

class JobDetailsSceneInteractor:  JobDetailsSceneDataStore
{
    var selectedJob: JobModel
    
  var presenter: JobDetailsScenePresentationLogic?
 
//MARK: object lifeCycle
    init(presenter: JobDetailsScenePresentationLogic, selectedJob: JobModel ) {
        self.presenter = presenter
        self.selectedJob = selectedJob
    }
  
  // MARK: Do something
}

extension JobDetailsSceneInteractor: JobDetailsSceneBusinessLogic {
    func getDetails(request: JobDetailsScene.ShowDetails.Request) {
        let response = JobDetailsScene.ShowDetails.Response(data: selectedJob)
        presenter?.presentJobDetails(response: response)
    }
    
    
}
