//
//  CategoriesInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 05.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoriesBusinessLogic
{
    func passCategory(request: Categories.FavoriteCategory.Request)
}

protocol CategoriesDataStore
{
    var passingCategories: [String] { get }
}

class CategoriesInteractor:  CategoriesDataStore
{
    // MARK: Clean components
  var presenter: CategoriesPresentationLogic?

    //MARK: passing data conteiner
    
  var passingCategories: [String] = []
 
    // MARK: Object Lifecycle
    
    init(presenter: CategoriesPresentationLogic ) {
        self.presenter = presenter
    }
}

//MARK: BusinessLogic methods

extension CategoriesInteractor: CategoriesBusinessLogic {
    func passCategory(request: Categories.FavoriteCategory.Request) {
        self.passingCategories = request.favoriteCategory
        presenter?.presentHomeScene(response: Categories.FavoriteCategory.Response())
    }
}
