//
//  CategoriesRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 05.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoriesRoutingLogic {
   func navigateToHomeScene()
}

protocol CategoriesDataPassing {
  var dataStore: CategoriesDataStore? { get }
}

class CategoriesRouter: CategoriesDataPassing {
    // MARK: Clean components
  weak var viewController: CategoriesViewController?
  var dataStore: CategoriesDataStore?

    // MARK: Object Lifecycle

    init(dataStore: CategoriesDataStore) {
        self.dataStore = dataStore
    }

    func  navigateToDetailsEditor(vc: UIViewController) {
        self.viewController?.present(vc, animated: true)
    }
}
// MARK: Routing Logic methods/ Navigation

extension CategoriesRouter: CategoriesRoutingLogic {
    func navigateToHomeScene() {
        guard let selectedCategory  = dataStore?.passingCategories else { return }
        let tabbarVc = TabBarViewController()
        tabbarVc.passingData = selectedCategory
        UserDefaults.standard.set(true, forKey: "ISUSERLOGGEDIN")
        viewController?.view.window?.rootViewController = tabbarVc
        viewController?.view.window?.makeKeyAndVisible()
    }
}
