//
//  CategoriesRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 05.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CategoriesRoutingLogic
{
    func navigateToDetailsEditor(vc: UIViewController)
}

protocol CategoriesDataPassing
{
  var dataStore: CategoriesDataStore? { get }
}

class CategoriesRouter: NSObject, CategoriesRoutingLogic, CategoriesDataPassing
{
  weak var viewController: CategoriesViewController?
  var dataStore: CategoriesDataStore?
  
  // MARK: Routing
  


  // MARK: Navigation
  
    func  navigateToDetailsEditor(vc: UIViewController) {
        self.viewController?.present(vc, animated: true)
    }
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CategoriesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
