//
//  CategoriesModels.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 05.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Categories {
  // MARK: Use cases

  enum FavoriteCategory {
    struct Request {
        let favoriteCategory: [String]
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
    enum CategoriesField {
        static let categoriesFields = ["All", "Art & Design", "Programming", "Marketing", "Sales", "Healthycare", "Content Writer", "Finance", "Food & Restourant", "Construction"]
    }
}
