//
//  CategoriesPresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 05.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoriesPresentationLogic {
    func presentHomeScene(response: Categories.FavoriteCategory.Response)
}

final class CategoriesPresenter: CategoriesPresentationLogic {
   
  weak var viewController: CategoriesDisplayLogic?
  
  // MARK: resentationLogic methods
    
    func presentHomeScene(response: Categories.FavoriteCategory.Response) {
        viewController?.displayHomeScene(viewModel: Categories.FavoriteCategory.ViewModel())
    }
    
}
