//
//  FavoritesSceneInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 18.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData


protocol FavoritesSceneBusinessLogic
{
    func getFavorites(request: FavoritesScene.GetFavoriteJobs.Request)
}

protocol FavoritesSceneDataStore
{
  //var name: String { get set }
}

class FavoritesSceneInteractor:  FavoritesSceneDataStore
{
    var container = [JobModel]()
    
    func doSomething(request: FavoritesScene.GetFavoriteJobs.Request) {
    
        }
        
    
    
  var presenter: FavoritesScenePresentationLogic?
  var worker: FavoritesSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
    init(presenter: FavoritesScenePresentationLogic, worker: FavoritesSceneWorker) {
        self.presenter = presenter
        self.worker = worker
    }

}

extension FavoritesSceneInteractor: FavoritesSceneBusinessLogic {
    func getFavorites(request: FavoritesScene.GetFavoriteJobs.Request) {
        guard let response =  worker?.getFavorites() else { return }
        // to do unwrap!
        response.forEach({ favorites in
            self.container.append(JobModel(logoImage: favorites.image!, brand: favorites.employer!, jobTitle: favorites.jobTitle!, location: favorites.location ?? "Tbilisi", jobType: favorites.jobTitle ?? "Full-time", category: favorites.category ?? " HR", sallary: Int(favorites.salary ) ))
        })
        presenter?.presentFavorites(response: FavoritesScene.GetFavoriteJobs.Response(data: container))

    }
    
    
}
