//
//  FavoritesSceneRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 18.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesSceneRoutingLogic {
}

protocol FavoritesSceneDataPassing {
  var dataStore: FavoritesSceneDataStore? { get }
}

final class FavoritesSceneRouter: FavoritesSceneRoutingLogic, FavoritesSceneDataPassing {
  weak var viewController: FavoritesSceneViewController?
  var dataStore: FavoritesSceneDataStore?
  
    init(dataStore: FavoritesSceneDataStore) {
        self.dataStore = dataStore
    }

}
