//
//  FavoritesSceneViewController.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 18.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol FavoritesSceneDisplayLogic: AnyObject {
    func displayFavoriteJobs(viewModel: FavoritesScene.GetFavoriteJobs.ViewModel)
}

final class FavoritesSceneViewController: UIViewController {
    
    //MARK: Clean Components
    
    var interactor: FavoritesSceneBusinessLogic?
    var router: (FavoritesSceneRoutingLogic & FavoritesSceneDataPassing)?
    
    var dataSource = [JobModel]()
    
    //MARK: UI
    
    lazy var tableView: UITableView = {
        let v = UITableView()
        v.dataSource = self
        v.delegate = self
        v.registerClass(class: JobsTableViewCell.self)
        
        return v
    }()
    
    // MARK: Object lifecycle
    
    init(interactor: FavoritesSceneBusinessLogic, router: (FavoritesSceneRoutingLogic & FavoritesSceneDataPassing)) {
        self.interactor = interactor
        self.router = router
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        interactor?.getFavorites(request: FavoritesScene.GetFavoriteJobs.Request())
        setUpUi()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        interactor?.getFavorites(request: FavoritesScene.GetFavoriteJobs.Request())
    }
    
    //MARK: Private methods
    
    private func setTipsTableData(data: [JobModel]) {
        self.dataSource = data
        self.tableView.reloadData()
    }
    
    // MARK: Setup UI
    
    private func setUpUi() {
        view.addSubview(tableView)
        tableView.anchor(top: view.safeAreaLayoutGuide.topAnchor, left: view.leftAnchor, bottom: view.bottomAnchor, right: view.rightAnchor, paddingTop: 20, paddingLeft: 10, paddingBottom: 10, paddingRight: 10)
    }
    
}
//MARK: DisplayLogic Methods

extension FavoritesSceneViewController: FavoritesSceneDisplayLogic {
    func displayFavoriteJobs(viewModel: FavoritesScene.GetFavoriteJobs.ViewModel) {
        self.setTipsTableData(data: viewModel.data)
    }
}
//MARK: CollectionViewDataSource

extension FavoritesSceneViewController : UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        dataSource.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.deque(class: JobsTableViewCell.self, for: indexPath)
        cell.configureCell(with: dataSource[indexPath.row])
        cell.shadowedtoView()
        return cell
    }
}

extension FavoritesSceneViewController: UITableViewDelegate {
    
}
