//
//  FavoritesSceneWorker.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 18.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol FavoritesSceneWorkerLogic {
    func getFavorites() -> [Favorites]
}

class FavoritesSceneWorker: FavoritesSceneWorkerLogic
{
    var coreDataManager: CoreDataManaager
    init(coreDataManager: CoreDataManaager) {
        self.coreDataManager = coreDataManager
    }
    
    func getFavorites() -> [Favorites] {
        coreDataManager.featchFavorites(fromEntity: "Favorites", by: "isFavorite == true")
    }
}
