//
//  SettingsSceneInteractor.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsSceneBusinessLogic {
    func logOut(request: SettingsScene.Settings.Request)
}

protocol SettingsSceneDataStore {
}

final class SettingsSceneInteractor: SettingsSceneBusinessLogic, SettingsSceneDataStore {
    
  var presenter: SettingsScenePresentationLogic?
  
  // MARK: Object lifeCycle
    
    init(presenter: SettingsScenePresentationLogic) {
        self.presenter = presenter
    }
  
    func logOut(request: SettingsScene.Settings.Request) {
        presenter?.presentAuthScene(response: SettingsScene.Settings.Response())
    }
}
