//
//  SettingsScenePresenter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsScenePresentationLogic {
    func presentSomething(response: SettingsScene.Settings.Response)
}

class SettingsScenePresenter: SettingsScenePresentationLogic {
  weak var viewController: SettingsSceneDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: SettingsScene.Settings.Response)
  {
   
  }
}
