//
//  SettingsSceneRouter.swift
//  JobLabFinal
//
//  Created by Natia's Mac on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsSceneRoutingLogic {
}

protocol SettingsSceneDataPassing {
  var dataStore: SettingsSceneDataStore? { get }
}

final class SettingsSceneRouter: SettingsSceneRoutingLogic, SettingsSceneDataPassing {
  weak var viewController: SettingsSceneViewController?
  var dataStore: SettingsSceneDataStore?
    init(dataStore: SettingsSceneDataStore) {
        self.dataStore = dataStore
    }
}
